### ISSUE TITLE
Parsing Error for high precision double values 

### ISSUE THREAD

**Issue by oliveralka** [dfermin/lucXor#6]
We ran into an issue using luciphor2 with parsing high precision double values in the mzML files: 

luciphor2 failed with:

`umich.ms.fileio.exceptions.FileParsingException: java.lang.NumberFormatException: Too many digits - Overflow`

It seems that the "javolution"  library is not able to parse doubles which have more than 19 digits. 

https://github.com/chhh/MSFTBX/blob/master/MSFileToolbox/src/main/java/umich/ms/fileio/filetypes/mzml/MZMLMultiSpectraParser.java#L286

Error:
```
Exception in thread "main" umich.ms.fileio.exceptions.FileParsingException: java.lang.NumberFormatException: Too many digits - Overflow
	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parseScan(AbstractXMLBasedDataSource.java:679)
	at lucxor.globals.read_mzML(globals.java:652)
	at lucxor.globals.read_in_spectra(globals.java:622)
	at lucxor.LucXor.main(LucXor.java:71)
Caused by: java.lang.NumberFormatException: Too many digits - Overflow
	at javolution.text.TypeFormat.parseDouble(TypeFormat.java:518)
	at javolution.text.TypeFormat.parseDouble(TypeFormat.java:579)
	at javolution.text.CharArray.toDouble(CharArray.java:481)
	at umich.ms.fileio.filetypes.mzml.MZMLMultiSpectraParser.tagCvParamStart(MZMLMultiSpectraParser.java:586)
	at umich.ms.fileio.filetypes.mzml.MZMLMultiSpectraParser.call(MZMLMultiSpectraParser.java:195)
	at umich.ms.fileio.filetypes.mzml.MZMLMultiSpectraParser.call(MZMLMultiSpectraParser.java:57)
	at umich.ms.fileio.filetypes.xmlbased.AbstractXMLBasedDataSource.parseScan(AbstractXMLBasedDataSource.java:669)
	... 3 more
```

**Comment by chhh** [comment]
Hi Oliver,
1) I think this is more or less the correct behavior - an 8 byte "double" can only have 15-17 digits of precision (it's a complicated topic overall). Parsing something with 19 digits would be loss of precision and require a specialized numeric type.
The exception you see is thrown deliberately, not just by neglect:
https://github.com/chhh/javolution-msftbx/blob/1ae76375165dbf89b243533863b43de0c994422c/src/main/java/javolution/text/TypeFormat.java#L518
2)
